name: wbnb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipython
  - dask
  - gdal >=1.11
  - matplotlib
  - geopandas
  - geojson
  - pyproj
  - ca-certificates
  - certifi
  - openssl
  - requests
  - numpy
  - pandas
  - shapely
  - dask-geopandas
  - planetary-computer
  - ipykernel
  - pip
  - pip:
    - pystac
    - pystac-client
    - rasterio
    - pyproj
    - stackstac
    - osmnx
    - fiona
  
